"""HyDE — Hypothetical Document Embeddings retriever.

Implements SPEC-RAG-001: generates a hypothetical document that would answer
the query, embeds it, and uses the resulting vector to search the store. This
narrows the semantic gap on abstract / "why"-style questions where the query
looks very different from the documents that actually answer it.

Example::

    from lightagent.rag.hyde import HyDERetriever
    from lightagent.rag.vector_store import ChromaVectorStore

    store = ChromaVectorStore()
    retriever = HyDERetriever(vector_store=store)
    result = await retriever.search("Why does LangGraph use StateGraph?", k=5)
    print(result.hypothesis)  # the generated hypothetical answer
    print(result.chunks)  # retrieved chunks
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from langchain_core.messages import HumanMessage, SystemMessage

from lightagent.core.config import get_settings
from lightagent.core.exceptions import HyDEError
from lightagent.core.logging import get_logger
from lightagent.monitoring.otel import OTelManager
from lightagent.providers.registry import ProviderRegistry
from lightagent.rag.crag import RetrievedChunk
from lightagent.rag.embeddings import EmbeddingsFactory
from lightagent.security.prompt_builder import SecurePromptBuilder

if TYPE_CHECKING:
    from lightagent.core.config import Settings
    from lightagent.rag.vector_store import ChromaVectorStore

logger = get_logger("lightagent.rag.hyde")

_DEFAULT_HYPOTHESIS_PROMPT = (
    "Write a short, plausible paragraph that directly answers the user's query "
    "as if it were extracted from a reference document. Do not hedge, do not "
    "ask for clarification — produce the hypothetical answer content only."
)


@dataclass
class HyDEResult:
    """Result of a HyDE search.

    Attributes:
        chunks: Chunks retrieved using the hypothesis embedding.
        hypothesis: Hypothetical document generated by the LLM.
        hypothesis_embedding: Vector of the hypothetical document (for
            debugging / inspection).
    """

    chunks: list[RetrievedChunk]
    hypothesis: str
    hypothesis_embedding: list[float]


class HyDERetriever:
    """Retriever that boosts recall by searching with a generated hypothesis.

    Instead of embedding the user query directly, the LLM first drafts a
    hypothetical document that would answer it. That document is then embedded
    and used to search the vector store. When the vocabulary gap between
    queries and documents is wide (e.g. "why" questions vs. technical
    explanations), HyDE tends to surface relevant chunks that a direct query
    embedding misses.

    Args:
        vector_store: Initialised :class:`ChromaVectorStore` to search.
        settings: LightAgent settings. ``None`` resolves via
            :func:`~lightagent.core.config.get_settings`.
        hypothesis_prompt: System prompt for hypothesis generation. ``None``
            uses the built-in default.
    """

    def __init__(
        self,
        vector_store: ChromaVectorStore,
        settings: Settings | None = None,
        hypothesis_prompt: str | None = None,
    ) -> None:
        self._store = vector_store
        self._settings = settings if settings is not None else get_settings()
        self._hypothesis_prompt = hypothesis_prompt or _DEFAULT_HYPOTHESIS_PROMPT
        self._llm = ProviderRegistry(settings=self._settings).get_llm()
        self._embeddings = EmbeddingsFactory.create(settings=self._settings)

    async def search(self, query: str, k: int = 5) -> HyDEResult:
        """Generate a hypothesis for *query* and search the store with it.

        Args:
            query: Raw user query.
            k: Maximum number of chunks to return.

        Returns:
            :class:`HyDEResult` with retrieved chunks, the hypothesis text,
            and the hypothesis embedding vector.

        Raises:
            HyDEError: If hypothesis generation or embedding fails.
        """
        otel = OTelManager()
        with otel.start_span("hyde.search") as span:
            span.set_attribute("lightagent.query_len", len(query))
            span.set_attribute("lightagent.k", k)

            hypothesis = await self._generate_hypothesis(query)
            span.set_attribute("lightagent.hypothesis_len", len(hypothesis))

            hypothesis_embedding = await self._embed_hypothesis(hypothesis)
            span.set_attribute("lightagent.hypothesis_embedding_dims", len(hypothesis_embedding))

            raw_results = self._store.similarity_search(hypothesis, k=k)
            chunks: list[RetrievedChunk] = []
            for i, (doc, score) in enumerate(raw_results):
                chunks.append(
                    RetrievedChunk(
                        source=doc.metadata.get("source", "unknown"),
                        chunk_id=doc.metadata.get("chunk_id", str(i)),
                        relevance_score=score,
                        content=doc.page_content,
                    )
                )
            span.set_attribute("lightagent.num_results", len(chunks))
            otel.increment_counter("rag_queries")

            logger.info(
                "hyde_search_done",
                result_count=len(chunks),
                hypothesis_len=len(hypothesis),
            )
            return HyDEResult(
                chunks=chunks,
                hypothesis=hypothesis,
                hypothesis_embedding=hypothesis_embedding,
            )

    async def _generate_hypothesis(self, query: str) -> str:
        """Ask the LLM for a hypothetical answer to *query*.

        Raises:
            HyDEError: If the LLM call fails.
        """
        builder = SecurePromptBuilder()
        messages = builder.build(system=self._hypothesis_prompt, user=query)
        lc_messages = [
            SystemMessage(content=messages[0]["content"]),
            HumanMessage(content=messages[1]["content"]),
        ]
        try:
            response = await self._llm.ainvoke(lc_messages)
        except Exception as exc:
            logger.warning("hyde_hypothesis_error", error=str(exc))
            raise HyDEError(f"Hypothesis generation failed: {exc}") from exc
        return str(response.content).strip()

    async def _embed_hypothesis(self, hypothesis: str) -> list[float]:
        """Embed the hypothesis for debugging / downstream inspection.

        Raises:
            HyDEError: If the embeddings call fails.
        """
        try:
            return list(self._embeddings.embed_query(hypothesis))
        except Exception as exc:
            logger.warning("hyde_embed_error", error=str(exc))
            raise HyDEError(f"Hypothesis embedding failed: {exc}") from exc


__all__ = ["HyDEResult", "HyDERetriever"]
