"""LightAgent wrapper for the Claude Code skill: README.

Auto-generated by RemoteSkillInstaller
(lightagent.skills.remote_installer).

Source repository: https://github.com/anthropics/skills
Original skill   : README
"""

from __future__ import annotations

from pathlib import Path

from langchain_core.tools import BaseTool, tool

from lightagent.skills.base import BaseSkill, SkillMetadata

# Load the original skill content once at import time.
_SKILL_CONTENT: str = (
    Path(__file__).parent / 'README.md'
).read_text(encoding="utf-8")


class ReadmeSkill(BaseSkill):
    """LightAgent wrapper for the Claude Code skill 'README'."""

    @property
    def metadata(self) -> SkillMetadata:
        """Return skill metadata."""
        return SkillMetadata(
            name='README',
            description="> **Note:** This repository contains Anthropic's implementation of skills for Claude. For information about the Agent Sk",
            version='1.0.0',
            author="anthropics",
            safe_to_auto_activate=False,
            tags=['claude-code', 'imported'],
        )

    def get_tools(self) -> list[BaseTool]:
        """Return the tools provided by this skill.

        Returns:
            A list containing the skill-guide retrieval tool.
        """

        @tool
        def get_README_guide(query: str = "") -> str:
            """Get instructions and guidance for the README skill.

            Args:
                query: Optional keyword to filter content lines.
                    When empty, returns the full guide.

            Returns:
                Full skill instructions, or lines matching *query*.
            """
            if query:
                matched = [
                    ln
                    for ln in _SKILL_CONTENT.splitlines()
                    if query.lower() in ln.lower()
                ]
                return "\n".join(matched) if matched else _SKILL_CONTENT
            return _SKILL_CONTENT

        return [get_README_guide]
